### ISSUE TITLE
Bootloop on Redmi Note 10S (rosemary)

### ISSUE THREAD

**Issue by ayusc** [R0rt1z2/kaeru#43]
I tried to build kaeru for rosemary on stock firmware 

Here are the logs from terminal:

```
root@ayus[05:33:46 PM]:~/kaeru$ ./build.sh rosemary lk.img
[INFO] Starting build process for device: rosemary
[STEP] Cleaning build environment
[SUCCESS] Environment cleaned
[STEP] Building configuration for rosemary
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  SHIPPED scripts/kconfig/zconf.tab.c
  SHIPPED scripts/kconfig/lex.zconf.c
  SHIPPED scripts/kconfig/zconf.hash.c
  HOSTCC  scripts/kconfig/zconf.tab.o
In file included from scripts/kconfig/zconf.tab.c:2503:
In function ‘dep_stack_insert’,
    inlined from ‘sym_check_print_recursive’ at scripts/kconfig/symbol.c:977:3,
    inlined from ‘sym_check_deps’ at scripts/kconfig/symbol.c:1148:3:
scripts/kconfig/symbol.c:953:19: warning: storing the address of local variable ‘cv_stack’ in ‘check_top’ [-Wdangling-pointer=]
  953 |         check_top = stack;
      |         ~~~~~~~~~~^~~~~~~
scripts/kconfig/symbol.c: In function ‘sym_check_deps’:
scripts/kconfig/symbol.c:974:26: note: ‘cv_stack’ declared here
  974 |         struct dep_stack cv_stack;
      |                          ^~~~~~~~
scripts/kconfig/symbol.c:944:4: note: ‘check_top’ declared here
  944 | } *check_top;
      |    ^~~~~~~~~
  HOSTLD  scripts/kconfig/conf
#
# configuration written to .config
#
[INFO] Building with 2 cores
scripts/kconfig/conf --silentoldconfig Kconfig
arm-linux-gnueabihf-gcc -E arch/arm/linker.lds.S -P -o arch/arm/linker.lds
make: arm-linux-gnueabihf-gcc: Not a directory
make: *** [Makefile:377: arch/arm/linker.lds] Error 127
[ERROR] Build failed

```

**Comment by shomykohai** [comment]
Looks like an issue with the compiler to me.
Can you try building in the docker container?

```sh
~/kaeru $ ./docker_run.sh
# ./build.sh rosemary lk.img
```

**Comment by ayusc** [comment]
sudo apt install gcc-arm-linux-gnueabihf

This fixed the issue for me.

**Comment by ayusc** [comment]
Hi, i flashed the generated lk.bin but the command `fastboot oem bldr_spoof` isn't working and neither `fastboot oem kaeru-version` 
Is this device not yet fully supported (cuz i see it exists int he config) ?

```ayus@AYUS:~/kaeru$ ./build.sh rosemary '/home/ayus/.var/app/org.telegram.desktop/data/TelegramDesktop/tdata/temp_data/lk.img' 
[INFO] Starting build process for device: rosemary
[STEP] Cleaning build environment
[SUCCESS] Environment cleaned
[STEP] Building configuration for rosemary
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  SHIPPED scripts/kconfig/zconf.tab.c
  SHIPPED scripts/kconfig/lex.zconf.c
  SHIPPED scripts/kconfig/zconf.hash.c
  HOSTCC  scripts/kconfig/zconf.tab.o
In file included from scripts/kconfig/zconf.tab.c:2503:
In function ‘dep_stack_insert’,
    inlined from ‘sym_check_print_recursive’ at scripts/kconfig/symbol.c:977:3,
    inlined from ‘sym_check_deps’ at scripts/kconfig/symbol.c:1148:3:
scripts/kconfig/symbol.c:953:19: warning: storing the address of local variable ‘cv_stack’ in ‘check_top’ [-Wdangling-pointer=]
  953 |         check_top = stack;
      |         ~~~~~~~~~~^~~~~~~
scripts/kconfig/symbol.c: In function ‘sym_check_deps’:
scripts/kconfig/symbol.c:974:26: note: ‘cv_stack’ declared here
  974 |         struct dep_stack cv_stack;
      |                          ^~~~~~~~
scripts/kconfig/symbol.c:944:4: note: ‘check_top’ declared here
  944 | } *check_top;
      |    ^~~~~~~~~
  HOSTLD  scripts/kconfig/conf
#
# configuration written to .config
#
[INFO] Building with 2 cores
scripts/kconfig/conf --silentoldconfig Kconfig
arm-linux-gnueabihf-gcc -E arch/arm/linker.lds.S -P -o arch/arm/linker.lds
  CC      main/main.o
  CC      arch/arm/cache.o
  CC      arch/arm/ops.o
  LD      main/built-in.o
  CC      board/xiaomi/board-rosemary.o
  AR      arch/lib.a
  CC      drivers/uart/mtk_uart.o
  LD      drivers/uart/built-in.o
  CC      drivers/usbdl/mtk_usbdl.o
  LD      drivers/usbdl/built-in.o
  AR      board/lib.a
  CC      drivers/wdt/mtk_wdt.o
  CC      lib/libc/string.o
  LD      drivers/wdt/built-in.o
  LD      drivers/built-in.o
  CC      lib/debug/debug.o
  CC      lib/common.o
  CC      lib/bootmode.o
  CC      lib/fastboot.o
  LD      lib/built-in.o
  LD      kaeru.o
  OBJCOPY kaeru
arm-linux-gnueabihf-objcopy -O binary kaeru.o kaeru
[SUCCESS] Build completed successfully
[STEP] Applying patches and generating rosemary-kaeru.bin
bss start: 0x4c58928c -> 0x4c58b1dc
code size: 1610380 -> 1618393
payload injection point: 0x4c58928c
payload padding: 7 bytes
partition end padding: 7 bytes
unaligned partition padding: 4 bytes
final next partition offset: 0x18b3e0
patched bootloader written to rosemary-kaeru.bin!
[SUCCESS] Patching completed: rosemary-kaeru.bin created (1785943 bytes)
[SUCCESS] Build process completed successfully
```

In the build logs i can see this text which looks sus: `unaligned partition padding: 4 ### ### bytes`

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/bcead9c6-c2a4-4162-9683-dced49284055" />

**Comment by shomykohai** [comment]
The device probably needs stage1 to be ported to it, sometimes it's possible for kaeru to fail loading.
To confirm this, can you send me your expdb, and lk as well so that I can find the addresses for stage1?

**Comment by ayusc** [comment]
Here it is: [rosemary.zip](https://github.com/user-attachments/files/24243675/rosemary.zip)
I forgot to mention that the device is bootlooping, however it can enter bootloader with the patched lk

Hope fastboot oem bldr_spoof can be used on this device right ? 
And does spoofing allows the device to pass play integrity checks(at least MEETS_DEVICE_INTEGRITY) even with a unlocked bl ?

**Comment by shomykohai** [comment]
> Here it is: [rosemary.zip](https://github.com/user-attachments/files/24243675/rosemary.zip)
> I forgot to mention that the device is bootlooping, however it can enter bootloader with the patched lk
> 
> Hope fastboot oem bldr_spoof can be used on this device right ? 
> And does spoofing allows the device to pass play integrity checks(at least MEETS_DEVICE_INTEGRITY) even with a unlocked bl ?

it seems like this lk is not the same used to port kaeru, thus the addresses dont match, and thats why it says data abort in the logs.

I'll try finding the matching lk first and send a build with stage1 enabled

**Comment by ayusc** [comment]
> it seems like this lk is not the same used to port kaeru, thus the addresses dont match, and thats why it says data abort in the logs.
> 
> I'll try finding the matching lk first and send a build with stage1 enabled

I gave you the lk image from the last available stock firmware (indian region) which is based on MIUI 14.0.11.0

Are you sure that the lk image used to port kaeru was from this device only, cuz i see there is a other model POCO M5S which shares the same codename(with similar SoC and specs), but their firmwares are different, so does their lk images.

I am not sure whether the images from one device will work on the other even under the same codename, but if it should work i am ready to downgrade the firmware version just tell me from which firmware version (and region) the lk was taken from.

Any other help i can do, pls let me know :)

**Comment by ayusc** [comment]
Hi, any updates on this ?

@R0rt1z2 Do you remember which firmware u used to build this and which phone was it Redmi Note 10S or Poco M5S

**Comment by shomykohai** [comment]
> Hi, any updates on this ?
> 
> @R0rt1z2 Do you remember which firmware u used to build this and which phone was it Redmi Note 10S or Poco M5S

Sorry, I forgot about this and got busy these days.

Can you try with this?
https://github.com/TheMuppets/proprietary_vendor_xiaomi_rosemary/blob/lineage-22.2/radio/lk.img

**Comment by ayusc** [comment]
> > Hi, any updates on this ?
> > [@R0rt1z2](https://github.com/R0rt1z2) Do you remember which firmware u used to build this and which phone was it Redmi Note 10S or Poco M5S
> 
> Sorry, I forgot about this and got busy these days.
> 
> Can you try with this? https://github.com/TheMuppets/proprietary_vendor_xiaomi_rosemary/blob/lineage-22.2/radio/lk.img

Hi I tried the last update of Lineage 22.2 for this phone. With this version fastboot oem kaeru-version shows the version but other commands don't work, also bootloop issue is still there,  device is bootlooping if turned on, it stays on fastboot without any issues.

The build I used is here: https://lineage-archive.timschumi.net/build/35965

![Image](https://github.com/user-attachments/assets/e00769e5-a07c-4e12-b6f4-23576fc013a2)

**Comment by shomykohai** [comment]
> > > Hi, any updates on this ?
> > > [@R0rt1z2](https://github.com/R0rt1z2) Do you remember which firmware u used to build this and which phone was it Redmi Note 10S or Poco M5S
> > 
> > 
> > Sorry, I forgot about this and got busy these days.
> > Can you try with this? https://github.com/TheMuppets/proprietary_vendor_xiaomi_rosemary/blob/lineage-22.2/radio/lk.img
> 
> Hi I tried the last update of Lineage 22.2 for this phone. With this version fastboot oem kaeru-version shows the version but other commands don't work, also bootloop issue is still there, device is bootlooping if turned on, it stays on fastboot without any issues.
> 
> The build I used is here: https://lineage-archive.timschumi.net/build/35965
> 
> ![Image](https://github.com/user-attachments/assets/e00769e5-a07c-4e12-b6f4-23576fc013a2)

What does the screen show for kaeru version?
Like, can you send a picture?
We use it as a test to know if there's corruption happening.
Also, what LK are you using again?

**Comment by ayusc** [comment]
@shomykohai Sorry I realised the sha256sum of these two lk are different so I used git lfs pull to pull the original lk file from the link you send me, and the checksums of these two files matched exactly with the one you send me, I will shortly update you with the new build.

Edit: I tried again by flashing the new lk image, I also flashed the other vendor files inside the radio dir, I have also pasted a ss of the sha255sum for the lk.img to confirm I used exactly the one you send me.
I have pasted a pic of the fastboot screen there is nothing just the fastboot logo.

And this time the phone is booting with this lk image. (No bootloops) !
Just I got dm-verity corruption msg and asks to press power key to boot

<img src="https://github.com/user-attachments/assets/629ce6a5-2d79-49de-80dc-18bcd071f374" width="150">
<img src="https://github.com/user-attachments/assets/d40bf5a5-5fa3-4d48-83dc-12f40e12f571" width="150">
<img src="https://github.com/user-attachments/assets/18ebdda4-3855-474e-98a5-4eda19d72e29" width="150">

**Comment by shomykohai** [comment]
> [@shomykohai](https://github.com/shomykohai) Sorry I realised the sha256sum of these two lk are different so I used git lfs pull to pull the original lk file from the link you send me, and the checksums of these two files matched exactly with the one you send me, I will shortly update you with the new build.
> 
> Edit: I tried again by flashing the new lk image, I also flashed the other vendor files inside the radio dir, I have also pasted a ss of the sha255sum for the lk.img to confirm I used exactly the one you send me. I have pasted a pic of the fastboot screen there is nothing just the fastboot logo.
> 
> And this time the phone is booting with this lk image. (No bootloops) ! Just I got dm-verity corruption msg and asks to press power key to boot
> <img alt="" width="150" src="https://private-user-images.githubusercontent.com/144832717/530869019-629ce6a5-2d79-49de-80dc-18bcd071f374.jpg?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjcwNjA5MDQsIm5iZiI6MTc2NzA2MDYwNCwicGF0aCI6Ii8xNDQ4MzI3MTcvNTMwODY5MDE5LTYyOWNlNmE1LTJkNzktNDlkZS04MGRjLTE4YmNkMDcxZjM3NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIzMFQwMjEwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NzVmYjlkNzcxOTZkNTY5YzQ0MDU4NDlmOGUzN2ZlZTQ1NWE5N2NlZDA0YmE4ZDY3ZDg3ZTYxZGMzY2NiYjQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.i5wvtKvh3qW88GzwnLicbssyQg0ldfZHNDqStBGCXHU"> <img alt="" width="150" src="https://private-user-images.githubusercontent.com/144832717/530869021-d40bf5a5-5fa3-4d48-83dc-12f40e12f571.jpg?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjcwNjA5MDQsIm5iZiI6MTc2NzA2MDYwNCwicGF0aCI6Ii8xNDQ4MzI3MTcvNTMwODY5MDIxLWQ0MGJmNWE1LTVmYTMtNGQ0OC04M2RjLTEyZjQwZTEyZjU3MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIzMFQwMjEwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGYyMjc1ZDNhMWY5ZThkN2Y2MTRiNTg0MjgyNGQ3M2E2MjgzNDgxY2U3MDUxMjJkMzNiMjAyZWVmOTEwMWRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CCDrAhKSLiJ9CSDYQivU9OxvOz2CW3zG6eupsRtPtks"> <img alt="" width="150" src="https://private-user-images.githubusercontent.com/144832717/530869839-18ebdda4-3855-474e-98a5-4eda19d72e29.jpg?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjcwNjA5MDQsIm5iZiI6MTc2NzA2MDYwNCwicGF0aCI6Ii8xNDQ4MzI3MTcvNTMwODY5ODM5LTE4ZWJkZGE0LTM4NTUtNDc0ZS05OGE1LTRlZGExOWQ3MmUyOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIzMFQwMjEwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDg3NDUwMzdjYjNlZDVmODY1M2JlNzI2Yjk1NWJmYzUxMzJmMjAxNTRhNzljZDY5NzdiOTQ1OTZkZDAwYjliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DO2qwm9KdrOBs0aZ9WR9M_G_QqOWlQW7KvABDlquoaU">

Good! 
Just noticed the board file for rosemary is also missing the fastboot command for bldr_spoof (hence why unknown command), but at least now we know kaeru is stable.
Tomorrow when I'll have time I'll fix the board file and port stage 1 too, so that we can be sure there will be no issue.
Thanks for testing the lk.

**Comment by shomykohai** [comment]
Hi @ayusc, can you try this build of kaeru?
I added both support for stage1 and the lock spoof cmd.

[rosemary-kaeru.bin.zip](https://github.com/user-attachments/files/24387897/rosemary-kaeru.bin.zip)

**Comment by ayusc** [comment]
![Image](https://github.com/user-attachments/assets/cfc5cc89-b7ac-4e48-a040-092aa89aa693)
![Image](https://github.com/user-attachments/assets/71582b94-d5a2-4b0c-af12-2b0303f538e8)

Lock spoof command isn't working and isn't there supposed to be some text in the fastboot screen (like kaeru version and banner) ?

Also tell me all the available kaeru commands so I can test them properly.

Happy New Year 🎊🎉

**Comment by shomykohai** [comment]
Hi @ayusc, can you please try this build? I forgot to *actually* register the lock spoof cmd in the previous build

[rosemary-kaeru2.bin.zip](https://github.com/user-attachments/files/24402235/rosemary-kaeru2.bin.zip)

**Comment by ayusc** [comment]
> Hi [@ayusc](https://github.com/ayusc), can you please try this build? I forgot to _actually_ register the lock spoof cmd in the previous build
> 
> [rosemary-kaeru2.bin.zip](https://github.com/user-attachments/files/24402235/rosemary-kaeru2.bin.zip)

Hi, thanks now the fastboot bldr_spoof command works but issue is the device thinks it locked, any fastboot flash and fastboot oem command reports that it can't use in locked state, which shouldn't happen I guess, since this is just for spoofing not actually locking the bootloader.

Also I got bootloop (after using fastboot oem bldr_spoof on and fastboot erase userdata)
I will try again tomorrow by flashing lineage(with mtkclient) and redoing the steps.

**Comment by shomykohai** [comment]
> > Hi [@ayusc](https://github.com/ayusc), can you please try this build? I forgot to _actually_ register the lock spoof cmd in the previous build
> > [rosemary-kaeru2.bin.zip](https://github.com/user-attachments/files/24402235/rosemary-kaeru2.bin.zip)
> 
> Hi, thanks now the fastboot bldr_spoof command works but issue is the device thinks it locked, any fastboot flash and fastboot oem command reports that it can't use in locked state, which shouldn't happen I guess, since this is just for spoofing not actually locking the bootloader.
> 
> Also I got bootloop (after using fastboot oem bldr_spoof on and fastboot erase userdata) I will try again tomorrow by flashing lineage(with mtkclient) and redoing the steps.

Nice, just need to fix some addresses for fastboot cmd_handler then!
I'll send you a new build soon

**Comment by ayusc** [comment]
> Nice, just need to fix some addresses for fastboot cmd_handler then! I'll send you a new build soon

Thanks, please take your time to fix-up everything and give me a final stable version.

**Comment by shomykohai** [comment]
Please @ayusc, try this. I fixed some addresses and patterns that were not correct

[rosemary-kaeru3.bin.zip](https://github.com/user-attachments/files/24410388/rosemary-kaeru3.bin.zip)

**Comment by ayusc** [comment]
> Please [@ayusc](https://github.com/ayusc), try this. I fixed some addresses and patterns that were not correct
> 
> [rosemary-kaeru3.bin.zip](https://github.com/user-attachments/files/24410388/rosemary-kaeru3.bin.zip)

Hello mam, I tested the lk and the bootloop issue is still there, I have erased userdata, metadata and still didn't work, also I formatted data from recovery as well, but still it bootloops.
The bootloop happens only after enabling spoof, otherwise device boots fine.

However good thing is that now if allows me to flash partitions and use oem commands while spoofing is enabled.

![Image](https://github.com/user-attachments/assets/ca92bf32-3766-4475-8e74-c6f7a414c6c2)

**Comment by shomykohai** [comment]
Hi, make sure you are using vbmetas that are matched with your system partitions, it's mandatory for lock spoof to work

**Comment by ayusc** [comment]
> Hi, make sure you are using vbmetas that are matched with your system partitions, it's mandatory for lock spoof to work

I am using the vbmeta that came with the rom itself (lineage 21), anyways it's a recovery rom so I didn't mess up with any partition except the lk.

My steps were:
• Clean flash lineage 21 (through custom recovery)
• Enter fastboot, flash lk to both slots
• fastboot reboot bootloader
• Enable bootloader spoofing 
• Format userdata
• Reboot

Hope I didn't need to patch the vbmeta with --disable-verity and --disable-verification.

**Comment by ayusc** [comment]
@shomykohai Today I tested again, and I can confirm the issue is only happening after enabling bldr_spoof, as I turn it off erase userdata and reboot again phone boots up.

This time I am sure I did everything properly, even I flashed Lineage to both slots and also can confirm that your lk is booting fine on both the slots but just as I enable the bldr_spoof bootloop occurs.

**Comment by shomykohai** [comment]
> @shomykohai Today I tested again, and I can confirm the issue is only happening after enabling bldr_spoof, as I turn it off erase userdata and reboot again phone boots up.
> 
> This time I am sure I did everything properly, even I flashed Lineage to both slots and also can confirm that your lk is booting fine on both the slots but just as I enable the bldr_spoof bootloop occurs.

Curious, wonder if it's crashing after reaching the linux kernel or before. If after, this has nothing to do with kaeru, but just libavb

**Comment by ayusc** [comment]
> > [@shomykohai](https://github.com/shomykohai) Today I tested again, and I can confirm the issue is only happening after enabling bldr_spoof, as I turn it off erase userdata and reboot again phone boots up.
> > This time I am sure I did everything properly, even I flashed Lineage to both slots and also can confirm that your lk is booting fine on both the slots but just as I enable the bldr_spoof bootloop occurs.
> 
> Curious, wonder if it's crashing after reaching the linux kernel or before. If after, this has nothing to do with kaeru, but just libavb

Can you tell me what log/dump should I send you so that you can check the fault.
I have attached the expdb dump.

[expdb.zip](https://github.com/user-attachments/files/24416776/expdb.zip)

**Comment by R0rt1z2** [comment]
> > > [@shomykohai](https://github.com/shomykohai) Today I tested again, and I can confirm the issue is only happening after enabling bldr_spoof, as I turn it off erase userdata and reboot again phone boots up.
> > > This time I am sure I did everything properly, even I flashed Lineage to both slots and also can confirm that your lk is booting fine on both the slots but just as I enable the bldr_spoof bootloop occurs.
> > 
> > 
> > Curious, wonder if it's crashing after reaching the linux kernel or before. If after, this has nothing to do with kaeru, but just libavb
> 
> Can you tell me what log/dump should I send you so that you can check the fault. I have attached the expdb dump.
> 
> [expdb.zip](https://github.com/user-attachments/files/24416776/expdb.zip)

It seems to jump to the kernel just fine. You should probably pull the logs from the `/sys/fs/pstore` folder. I’m 90% sure your issue is vbmeta.

**Comment by ayusc** [comment]
@R0rt1z2 @shomykohai I have attached the kernel logs, please have a look.

And, also tell me is there any hopes that kaeru will work on this device or not.

[pstore.zip](https://github.com/user-attachments/files/24417186/pstore.zip)

**Comment by shomykohai** [comment]
> [@R0rt1z2](https://github.com/R0rt1z2) [@shomykohai](https://github.com/shomykohai) I have attached the kernel logs, please have a look.
> 
> And, also tell me is there any hopes that kaeru will work on this device or not.
> 
> [pstore.zip](https://github.com/user-attachments/files/24417186/pstore.zip)

I don't find anything useful here unfortunately, but as @R0rt1z2 said, lk is indeed jumping to the kernel so it's not a kaeru issue, but what comes after.

Have you tried if it works with stock rom first?

**Comment by ayusc** [comment]
@shomykohai I tried that just a few mins ago and with the last lk you gave me, i am getting bootloop without even using bldr_spoof.

The device can enter fastboot with this lk and also shows the kaeru version and the bldr_spoof commands also work, but with stock ROM either it is on or off doesn't matter it just bootloops.

Can something be done, or kaeru can never work on this device ?

**Comment by shomykohai** [comment]
> [@shomykohai](https://github.com/shomykohai) I tried that just a few mins ago and with the last lk you gave me, i am getting bootloop without even using bldr_spoof.
> 
> The device can enter fastboot with this lk and also shows the kaeru version and the bldr_spoof commands also work, but with stock ROM either it is on or off doesn't matter it just bootloops.
> 
> Can something be done, or kaeru can never work on this device ?

Does it let you enter recovery?
If so, I'd say it's an issue with the libavb not kaeru, really, there's no other explanation.
Also, make sure you erased metadata too

**Comment by ayusc** [comment]
> > [@shomykohai](https://github.com/shomykohai) I tried that just a few mins ago and with the last lk you gave me, i am getting bootloop without even using bldr_spoof.
> > The device can enter fastboot with this lk and also shows the kaeru version and the bldr_spoof commands also work, but with stock ROM either it is on or off doesn't matter it just bootloops.
> > Can something be done, or kaeru can never work on this device ?
> 
> Does it let you enter recovery? If so, I'd say it's an issue with the libavb not kaeru, really, there's no other explanation. Also, make sure you erased metadata too

Yes I could enter recovery, and yes i also erased metadata still bootloop issue is there.

**Comment by shomykohai** [comment]
> Yes I could enter recovery, and yes i also erased metadata still bootloop issue is there.

This seem to be 100% a issue outside of kaeru, or at least related to what the kernel sees.

Can you grab somehow the kernel cmdline?

**Comment by ayusc** [comment]
> > Yes I could enter recovery, and yes i also erased metadata still bootloop issue is there.
> 
> This seem to be 100% a issue outside of kaeru, or at least related to what the kernel sees.
> 
> Can you grab somehow the kernel cmdline?

@shomykohai I am sorry but I sold that phone and instead bought a second-hand Realme 7 (salaa) since kaeru wasn't working on this device.

And regarding the kernel cmdline can't you get it from the boot.img if i gave you (using magiskboot) ?
I have pasted the boot image in split parts (i cant upload the zip entirely) 
Use `cat boot1.zip boot2.zip boot3.zip > boot.zip` to get the full zip.

I am closing the issue since I can't contribute to it anymore, if someone else having a Redmi Note 10S needs to run kaeru can continue the conversation...

[boot1.zip](https://github.com/user-attachments/files/24557672/boot1.zip)
[boot2.zip](https://github.com/user-attachments/files/24557688/boot2.zip)

**Comment by shomykohai** [comment]
> > > Yes I could enter recovery, and yes i also erased metadata still bootloop issue is there.
> > 
> > This seem to be 100% a issue outside of kaeru, or at least related to what the kernel sees.
> > 
> > Can you grab somehow the kernel cmdline?
> 
> @shomykohai I am sorry but I sold that phone and instead bought a second-hand Realme 7 (salaa) since kaeru wasn't working on this device.
> 



> And regarding the kernel cmdline can't you get it from the boot.img if i gave you (using magiskboot) ?
> I have pasted the boot image in split parts (i cant upload the zip entirely) 
> Use `cat boot1.zip boot2.zip boot3.zip > boot.zip` to get the full zip.
> 
> I am closing the issue since I can't contribute to it anymore, if someone else having a Redmi Note 10S needs to run kaeru can continue the conversation...
> 
> [boot1.zip](https://github.com/user-attachments/files/24557672/boot1.zip)
> [boot2.zip](https://github.com/user-attachments/files/24557688/boot2.zip)
> 

Unfortunately, the boot image can't give us the full cmd line we get from the bootloader :(
Thanks anyway though for the files!

**Comment by R0rt1z2** [comment]
https://github.com/R0rt1z2/kaeru/commit/ea2e0ac4e54ae0a7b2700fd82eb56d091431a2c3 adds support for bootloader lock spoofing on the Redmi Note 10S and its respective variants.

The implementation is based on the latest LK from Android 13 (`V14.0.17.0.TFFMIXM`).

**Comment by NCLnclNCL** [comment]
> [ea2e0ac](https://github.com/R0rt1z2/kaeru/commit/ea2e0ac4e54ae0a7b2700fd82eb56d091431a2c3) adds support for bootloader lock spoofing on the Redmi Note 10S and its respective variants.
> 
> The implementation is based on the latest LK from Android 13 (`V14.0.17.0.TFFMIXM`).



> > > > Yes I could enter recovery, and yes i also erased metadata still bootloop issue is there.
> > > 
> > > 
> > > This seem to be 100% a issue outside of kaeru, or at least related to what the kernel sees.
> > > Can you grab somehow the kernel cmdline?
> > 
> > 
> > [@shomykohai](https://github.com/shomykohai) I am sorry but I sold that phone and instead bought a second-hand Realme 7 (salaa) since kaeru wasn't working on this device.
> 
> > And regarding the kernel cmdline can't you get it from the boot.img if i gave you (using magiskboot) ?
> > I have pasted the boot image in split parts (i cant upload the zip entirely)
> > Use `cat boot1.zip boot2.zip boot3.zip > boot.zip` to get the full zip.
> > I am closing the issue since I can't contribute to it anymore, if someone else having a Redmi Note 10S needs to run kaeru can continue the conversation...
> > [boot1.zip](https://github.com/user-attachments/files/24557672/boot1.zip)
> > [boot2.zip](https://github.com/user-attachments/files/24557688/boot2.zip)
> 
> Unfortunately, the boot image can't give us the full cmd line we get from the bootloader :( Thanks anyway though for the files!

Send patched lk.img

**Comment by NCLnclNCL** [comment]
> Please [@ayusc](https://github.com/ayusc), try this. I fixed some addresses and patterns that were not correct
> 
> [rosemary-kaeru3.bin.zip](https://github.com/user-attachments/files/24410388/rosemary-kaeru3.bin.zip)



> Please [@ayusc](https://github.com/ayusc), try this. I fixed some addresses and patterns that were not correct
> 
> [rosemary-kaeru3.bin.zip](https://github.com/user-attachments/files/24410388/rosemary-kaeru3.bin.zip)

upload source, this working in redmi note 10s and in V14.0.11.0
V14.0.17.0.TFFMIXM is poco m5s, cause brick if flash

**Comment by NCLnclNCL** [comment]
> > > Yes I could enter recovery, and yes i also erased metadata still bootloop issue is there.
> > 
> > 
> > This seem to be 100% a issue outside of kaeru, or at least related to what the kernel sees.
> > Can you grab somehow the kernel cmdline?
> 
> [@shomykohai](https://github.com/shomykohai) I am sorry but I sold that phone and instead bought a second-hand Realme 7 (salaa) since kaeru wasn't working on this device.
> 
> And regarding the kernel cmdline can't you get it from the boot.img if i gave you (using magiskboot) ? I have pasted the boot image in split parts (i cant upload the zip entirely) Use `cat boot1.zip boot2.zip boot3.zip > boot.zip` to get the full zip.
> 
> I am closing the issue since I can't contribute to it anymore, if someone else having a Redmi Note 10S needs to run kaeru can continue the conversation...
> 
> [boot1.zip](https://github.com/user-attachments/files/24557672/boot1.zip) [boot2.zip](https://github.com/user-attachments/files/24557688/boot2.zip)



> > > Yes I could enter recovery, and yes i also erased metadata still bootloop issue is there.
> > 
> > 
> > This seem to be 100% a issue outside of kaeru, or at least related to what the kernel sees.
> > Can you grab somehow the kernel cmdline?
> 
> [@shomykohai](https://github.com/shomykohai) I am sorry but I sold that phone and instead bought a second-hand Realme 7 (salaa) since kaeru wasn't working on this device.
> 
> And regarding the kernel cmdline can't you get it from the boot.img if i gave you (using magiskboot) ? I have pasted the boot image in split parts (i cant upload the zip entirely) Use `cat boot1.zip boot2.zip boot3.zip > boot.zip` to get the full zip.
> 
> I am closing the issue since I can't contribute to it anymore, if someone else having a Redmi Note 10S needs to run kaeru can continue the conversation...
> 
> [boot1.zip](https://github.com/user-attachments/files/24557672/boot1.zip) [boot2.zip](https://github.com/user-attachments/files/24557688/boot2.zip)


File that she send you actually working, spoof working
